# Tugas 1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset_url="https://raw.githubusercontent.com/Theresia028/datamining/gh-pages/ds_salaries.csv"
data=pd.read_csv(dataset_url, index_col=0)

In [ ]:
data

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...
602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [ ]:
def diss(x,y):
  a = 2
  b = 0
  for col in ['salary','salary_in_usd']:
    if data[col][x] == data[col][y]:
      b+=1
    return (a-b)/a

Menghitung Dissimilarity

In [ ]:
print(diss(1,1))
print(diss(1,2))
print(diss(3,3))

0.5
1.0
0.5

# Tugas 2
**DISKRITISASI**

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data[:,:1] # we only take the first two features.
y = iris.target

In [3]:
x

array([[5.1],
       [4.9],
       [4.7],
       [4.6],
       [5. ],
       [5.4],
       [4.6],
       [5. ],
       [4.4],
       [4.9],
       [5.4],
       [4.8],
       [4.8],
       [4.3],
       [5.8],
       [5.7],
       [5.4],
       [5.1],
       [5.7],
       [5.1],
       [5.4],
       [5.1],
       [4.6],
       [5.1],
       [4.8],
       [5. ],
       [5. ],
       [5.2],
       [5.2],
       [4.7],
       [4.8],
       [5.4],
       [5.2],
       [5.5],
       [4.9],
       [5. ],
       [5.5],
       [4.9],
       [4.4],
       [5.1],
       [5. ],
       [4.5],
       [4.4],
       [5. ],
       [5.1],
       [4.8],
       [5.1],
       [4.6],
       [5.3],
       [5. ],
       [7. ],
       [6.4],
       [6.9],
       [5.5],
       [6.5],
       [5.7],
       [6.3],
       [4.9],
       [6.6],
       [5.2],
       [5. ],
       [5.9],
       [6. ],
       [6.1],
       [5.6],
       [6.7],
       [5.6],
       [5.8],
       [6.2],
       [5.6],
       [5.9],
       [6.1],
       [6.3],
       [6.1],
       [6.4],
       [6.6],
       [6.8],
       [6.7],
       [6. ],
       [5.7],
       [5.5],
       [5.5],
       [5.8],
       [6. ],
       [5.4],
       [6. ],
       [6.7],
       [6.3],
       [5.6],
       [5.5],
       [5.5],
       [6.1],
       [5.8],
       [5. ],
       [5.6],
       [5.7],
       [5.7],
       [6.2],
       [5.1],
       [5.7],
       [6.3],
       [5.8],
       [7.1],
       [6.3],
       [6.5],
       [7.6],
       [4.9],
       [7.3],
       [6.7],
       [7.2],
       [6.5],
       [6.4],
       [6.8],
       [5.7],
       [5.8],
       [6.4],
       [6.5],
       [7.7],
       [7.7],
       [6. ],
       [6.9],
       [5.6],
       [7.7],
       [6.3],
       [6.7],
       [7.2],
       [6.2],
       [6.1],
       [6.4],
       [7.2],
       [7.4],
       [7.9],
       [6.4],
       [6.3],
       [6.1],
       [7.7],
       [6.3],
       [6.4],
       [6. ],
       [6.9],
       [6.7],
       [6.9],
       [5.8],
       [6.8],
       [6.7],
       [6.7],
       [6.3],
       [6.5],
       [6.2],
       [5.9]])

In [4]:
df = pd.DataFrame(x,columns = ['sepal'])

In [21]:
df

     sepal
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0

[150 rows x 1 columns]

In [22]:
dataset_url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data=pd.read_csv(dataset_url)

In [23]:
data[['sepal_length']]

     sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [24]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [25]:
data['sepal_length']=est.fit_transform(data[['sepal_length']])

In [26]:
data['sepal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0
Name: sepal_length, Length: 150, dtype: float64

In [27]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['sepal_width']=est.fit_transform(data[['sepal_width']])

In [28]:
data['sepal_width']

0      2.0
1      1.0
2      2.0
3      1.0
4      2.0
      ...
145    1.0
146    0.0
147    1.0
148    2.0
149    1.0
Name: sepal_width, Length: 150, dtype: float64

In [29]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_length']=est.fit_transform(data[['petal_length']])

In [30]:
data['petal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: petal_length, Length: 150, dtype: float64

In [31]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_width']=est.fit_transform(data[['petal_width']])

In [32]:
data['petal_width']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    3.0
146    3.0
147    3.0
148    3.0
149    2.0
Name: petal_width, Length: 150, dtype: float64